export const AUTH_REQUEST_REGISTER = 'auth/REQUEST_REGISTER';
export const AUTH_RECEIVE_REGISTER = 'auth/RECEIVE_REGISTER';
export const AUTH_REQUEST_LOGIN = 'auth/REQUEST_LOGIN';
export const AUTH_RECEIVE_LOGIN = 'auth/RECEIVE_LOGIN';
export const AUTH_REQUEST_LOGOUT = 'auth/RECEIVE_LOGOUT';
export const AUTH_RECEIVE_LOGOUT = 'auth/RECEIVE_LOGOUT';
export const AUTH_RECEIVE_ERROR = 'auth/ERROR';

export const TODO_LIST_REQUEST_DATA = 'todos/REQUEST_LIST_DATA';
export const TODO_LIST_RECEIVE_DATA = 'todos/RECEIVE_LIST_DATA';
export const TODO_LIST_REQUEST_TOGGLE = 'todos/REQUEST_TOGGLE';
export const TODO_LIST_RECEIVE_TOGGLE = 'todos/RECEIVE_TOGGLE';
export const TODO_LIST_TOGGLE_ERROR = 'todos/TOGGLE_ERROR';
